"""Compatibilidad con imports del Sprint 0 y diagramas existentes."""

from paquetes.paquete1_usuarios_condominio.cu03_datos_condominio.serializers import CondominiumSerializer
from paquetes.paquete1_usuarios_condominio.cu04_sectores_unidades.serializers import SectorSerializer, UnitSerializer
from paquetes.paquete1_usuarios_condominio.cu05_residentes.serializers import ResidentSerializer
from paquetes.paquete1_usuarios_condominio.cu06_asociar_residentes_unidades.serializers import ResidentDirectorySerializer, ResidentUnitSerializer
from paquetes.paquete1_usuarios_condominio.cu07_personal.serializers import StaffSerializer
