"""Compatibilidad con imports del Sprint 0 y diagramas existentes."""

from paquetes.paquete1_usuarios_condominio.cu03_datos_condominio.views import CondominiumViewSet
from paquetes.paquete1_usuarios_condominio.cu04_sectores_unidades.views import SectorViewSet, UnitViewSet
from paquetes.paquete1_usuarios_condominio.cu05_residentes.views import ResidentViewSet
from paquetes.paquete1_usuarios_condominio.cu06_asociar_residentes_unidades.views import ResidentDirectoryViewSet, ResidentUnitViewSet
from paquetes.paquete1_usuarios_condominio.cu07_personal.views import StaffViewSet
