# Generated by Django 5.2.17 on 2026-08-09 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=80)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['-occurred_at'], name='idx_audit_occurred_at'), models.Index(fields=['actor_user', '-occurred_at'], name='idx_audit_actor_time'), models.Index(fields=['action_code', '-occurred_at'], name='idx_audit_action_time'), models.Index(fields=['resource_type', 'resource_id'], name='idx_audit_resource')],
            },
        ),
    ]
