# Generated by Django 5.2.17 on 2026-08-09 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominiums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonAreaSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField()),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'common_area_schedule',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=240)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completado'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agreement',
            },
        ),
        migrations.CreateModel(
            name='AgreementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community.agreement')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agreement_attachment',
            },
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('IN_PROGRESS', 'En progreso'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20)),
                ('minutes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assemblies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assembly',
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='community.assembly'),
        ),
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible'), ('MAINTENANCE', 'Mantenimiento'), ('INACTIVE', 'Inactiva')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_areas', to='condominiums.sector')),
            ],
            options={
                'db_table': 'common_area',
            },
        ),
        migrations.CreateModel(
            name='CommonAreaBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_from', models.DateTimeField()),
                ('blocked_until', models.DateTimeField()),
                ('reason', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('common_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='community.commonarea')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_area_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'common_area_block',
            },
        ),
    ]
