# Generated by Django 5.2.17 on 2026-08-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('condominiums', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commonareablock',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_area_blocks', to='maintenance.workorder'),
        ),
        migrations.AddField(
            model_name='commonareaschedule',
            name='common_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='community.commonarea'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='common_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='community.commonarea'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='condominiums.resident'),
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['-scheduled_at'], name='idx_assembly_schedule'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['status', 'due_at'], name='idx_agreement_status_due'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estimated_budget__isnull', True), ('estimated_budget__gte', 0), _connector='OR'), models.Q(('actual_cost__isnull', True), ('actual_cost__gte', 0), _connector='OR')), name='chk_agreement_costs'),
        ),
        migrations.AddConstraint(
            model_name='commonarea',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='chk_common_area_capacity'),
        ),
        migrations.AddIndex(
            model_name='commonareablock',
            index=models.Index(fields=['common_area', 'blocked_from', 'blocked_until'], name='idx_area_block_window'),
        ),
        migrations.AddConstraint(
            model_name='commonareablock',
            constraint=models.CheckConstraint(condition=models.Q(('blocked_until__gt', models.F('blocked_from'))), name='chk_area_block_dates'),
        ),
        migrations.AddConstraint(
            model_name='commonareaschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='chk_area_weekday'),
        ),
        migrations.AddConstraint(
            model_name='commonareaschedule',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='chk_area_schedule_time'),
        ),
        migrations.AddConstraint(
            model_name='commonareaschedule',
            constraint=models.UniqueConstraint(fields=('common_area', 'weekday', 'opens_at', 'closes_at'), name='uq_area_schedule'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['resident', '-start_at'], name='idx_resident_reservation'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['common_area', 'start_at'], name='idx_area_reservation'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='chk_reservation_dates'),
        ),
    ]
