# Generated by Django 5.2.17 on 2026-08-09 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systempermission',
            name='module',
            field=models.CharField(default='general', max_length=60),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_table='role_permission', related_name='roles', to='accounts.systempermission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='systempermission',
            name='code',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='apellidos'),
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='systempermission',
            table='system_permission',
        ),
        migrations.AlterModelTable(
            name='user',
            table='app_user',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=120)),
                ('document_type', models.CharField(choices=[('CI', 'Cédula de identidad'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], default='CI', max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=30, null=True)),
                ('document_complement', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'person',
                'ordering': ('last_name', 'first_name'),
                'indexes': [models.Index(fields=['last_name'], name='idx_person_last_name'), models.Index(fields=['document_number'], name='idx_person_document_number')],
                'constraints': [models.CheckConstraint(condition=models.Q(('document_number__isnull', True), models.Q(('document_number', ''), _negated=True), _connector='OR'), name='chk_person_document'), models.UniqueConstraint(condition=models.Q(('document_number__isnull', False)), fields=('document_type', 'document_number', 'document_complement'), name='uq_person_document')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.person'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_app_user_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_app_user_active'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', True), ('role__isnull', False), _connector='OR'), name='chk_user_role'),
        ),
    ]
