# Generated by Django 5.2.17 on 2026-08-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginattempt'),
        ('accounts', '0004_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
    ]
