# Generated by Django 5.2.17 on 2026-09-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260824_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='False mientras el Administrador no haya aprobado la solicitud de Residente.'),
        ),
    ]
