# Generated by Django 5.2.17 on 2026-10-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_user_is_approved'),
        ('condominiums', '0006_condominium_max_residents_condominium_max_units_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Tenant predeterminado para el usuario al iniciar sesión.')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la membresía está activa y puede operar en el tenant.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to='condominiums.condominium')),
                ('role', models.ForeignKey(blank=True, help_text='Rol asignado al usuario dentro de este condominio/tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_memberships', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_membership',
                'ordering': ('-is_default', 'condominium__name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'condominium'), name='uq_tenant_membership_user_condo')],
            },
        ),
    ]
