# Generated by Django 5.2.17 on 2026-10-04 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0006_condominium_max_residents_condominium_max_units_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Código único del plan (ej. 'basic', 'pro', 'enterprise')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre visible del plan', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Subtítulo o descripción comercial corta', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_bob', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio en Bolivianos (BOB)', max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Referencia en USD', max_digits=10)),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], default='MONTHLY', max_length=20)),
                ('max_units', models.PositiveIntegerField(default=50, help_text='Límite de unidades / departamentos')),
                ('max_residents', models.PositiveIntegerField(default=150, help_text='Límite de residentes')),
                ('features', models.JSONField(blank=True, default=list, help_text='Lista de características y módulos incluidos')),
                ('is_popular', models.BooleanField(default=False, help_text='Destacar como más popular en landing')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'saas_subscription_plan',
                'ordering': ('order', 'price_bob'),
            },
        ),
        migrations.CreateModel(
            name='SaaSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='bob', max_length=10)),
                ('provider', models.CharField(default='stripe', max_length=30)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('payment_intent_id', models.CharField(blank=True, default='', max_length=150)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_payments', to='condominiums.condominium')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenancy.subscriptionplan')),
            ],
            options={
                'db_table': 'saas_payment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Período de Prueba'), ('ACTIVE', 'Activa'), ('PAST_DUE', 'Pago Pendiente'), ('CANCELED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='TRIAL', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='condominiums.condominium')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenancy.subscriptionplan')),
            ],
            options={
                'db_table': 'saas_tenant_subscription',
            },
        ),
    ]
