# Generated by Django 5.2.17 on 2026-08-09 17:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_systempermission_is_active_systempermission_module_and_more'),
        ('condominiums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('DENIED', 'Denegado')], max_length=20)),
                ('validation_method', models.CharField(choices=[('QR', 'QR'), ('FACE', 'Facial'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('validation_result', models.CharField(choices=[('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('MANUAL_REVIEW', 'Revisión manual')], default='APPROVED', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('guard_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarded_access_events', to='condominiums.staff')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='accounts.person')),
            ],
            options={
                'db_table': 'access_event',
            },
        ),
        migrations.CreateModel(
            name='BiometricReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_image', models.CharField(blank=True, max_length=500)),
                ('embedding', models.BinaryField()),
                ('embedding_dim', models.SmallIntegerField()),
                ('model_name', models.CharField(max_length=80)),
                ('model_version', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrolled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_enrollments', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_references', to='condominiums.resident')),
            ],
            options={
                'db_table': 'biometric_reference',
            },
        ),
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_image', models.CharField(blank=True, max_length=500)),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('model_name', models.CharField(max_length=80)),
                ('model_version', models.CharField(max_length=40)),
                ('result', models.CharField(choices=[('MATCH', 'Coincidencia'), ('NO_MATCH', 'Sin coincidencia'), ('REVIEW', 'Revisión')], max_length=20)),
                ('human_confirmed', models.BooleanField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_verifications', to='security.accessevent')),
                ('biometric_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='security.biometricreference')),
                ('confirmed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_faces', to=settings.AUTH_USER_MODEL)),
                ('guard_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_verifications', to='condominiums.staff')),
                ('matched_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_verifications', to='condominiums.resident')),
            ],
            options={
                'db_table': 'face_verification',
            },
        ),
        migrations.CreateModel(
            name='SecurityShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('OPEN', 'Abierto'), ('CLOSED', 'Cerrado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20)),
                ('opening_notes', models.TextField(blank=True)),
                ('closing_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('guard_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_shifts', to='condominiums.staff')),
            ],
            options={
                'db_table': 'security_shift',
            },
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RECEIVED', 'Recibida'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('delivered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_handovers', to=settings.AUTH_USER_MODEL)),
                ('incoming_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_handovers', to='security.securityshift')),
                ('outgoing_shift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_handover', to='security.securityshift')),
                ('received_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_handovers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shift_handover',
            },
        ),
        migrations.CreateModel(
            name='ShiftLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('NOTE', 'Nota'), ('INCIDENT', 'Incidente'), ('ALERT', 'Alerta'), ('HANDOVER_NOTE', 'Entrega de turno')], default='NOTE', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='INFO', max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_logs', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_logs', to='condominiums.sector')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='security.securityshift')),
            ],
            options={
                'db_table': 'shift_log_entry',
            },
        ),
        migrations.CreateModel(
            name='VisitAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Autorizada'), ('ACTIVE', 'Activa'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='AUTHORIZED', max_length=20)),
                ('qr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorized_by_resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_visits', to='condominiums.resident')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_authorizations', to='condominiums.unit')),
                ('visitor_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_authorizations', to='accounts.person')),
            ],
            options={
                'db_table': 'visit_authorization',
            },
        ),
        migrations.AddField(
            model_name='accessevent',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='security.visitauthorization'),
        ),
        migrations.AddConstraint(
            model_name='biometricreference',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('resident',), name='uq_active_biometric_ref'),
        ),
        migrations.AddIndex(
            model_name='faceverification',
            index=models.Index(fields=['-verified_at'], name='idx_face_verify_time'),
        ),
        migrations.AddIndex(
            model_name='faceverification',
            index=models.Index(fields=['matched_resident', '-verified_at'], name='idx_face_resident_time'),
        ),
        migrations.AddConstraint(
            model_name='faceverification',
            constraint=models.CheckConstraint(condition=models.Q(('similarity_score__isnull', True), models.Q(('similarity_score__gte', 0), ('similarity_score__lte', 1)), _connector='OR'), name='chk_face_score'),
        ),
        migrations.AddConstraint(
            model_name='faceverification',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__isnull', True), models.Q(('threshold__gte', 0), ('threshold__lte', 1)), _connector='OR'), name='chk_face_threshold'),
        ),
        migrations.AddIndex(
            model_name='securityshift',
            index=models.Index(fields=['guard_staff', '-scheduled_start'], name='idx_shift_guard_start'),
        ),
        migrations.AddConstraint(
            model_name='securityshift',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='chk_shift_schedule'),
        ),
        migrations.AddConstraint(
            model_name='securityshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('guard_staff',), name='uq_guard_open_shift'),
        ),
        migrations.AddConstraint(
            model_name='shifthandover',
            constraint=models.CheckConstraint(condition=models.Q(('received_at__isnull', True), ('received_at__gte', models.F('delivered_at')), _connector='OR'), name='chk_handover_receive_time'),
        ),
        migrations.AddIndex(
            model_name='shiftlogentry',
            index=models.Index(fields=['shift', '-occurred_at'], name='idx_shift_log_time'),
        ),
        migrations.AddIndex(
            model_name='visitauthorization',
            index=models.Index(fields=['status', 'valid_from', 'valid_until'], name='idx_visit_status_window'),
        ),
        migrations.AddIndex(
            model_name='visitauthorization',
            index=models.Index(fields=['authorized_by_resident', '-valid_from'], name='idx_visit_resident_time'),
        ),
        migrations.AddIndex(
            model_name='visitauthorization',
            index=models.Index(fields=['unit', '-valid_from'], name='idx_visit_unit_time'),
        ),
        migrations.AddConstraint(
            model_name='visitauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='chk_visit_dates'),
        ),
        migrations.AddConstraint(
            model_name='visitauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('qr_expires_at__lte', models.F('valid_until'))), name='chk_visit_qr_expiry'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['authorization', '-occurred_at'], name='idx_access_auth_time'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['person', '-occurred_at'], name='idx_access_person_time'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['guard_staff', '-occurred_at'], name='idx_access_guard_time'),
        ),
    ]
