# Generated by Django 5.2.17 on 2026-10-04 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0005_sync_condominium_sequence'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='condominiums.unit'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='visitor_document_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='visitor_name',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
