# Generated by Django 5.2.17 on 2026-10-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0005_sync_condominium_sequence'),
        ('security', '0002_visitauthorization_qr_issued_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityshift',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_shifts', to='condominiums.condominium'),
        ),
        migrations.AddField(
            model_name='securityshift',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_security_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityshift',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securityshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
