# Generated by Django 5.2.17 on 2026-10-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_merge_visit_qr_access_events'),
        ('security', '0003_securityshift_condominium_and_more'),
    ]

    operations = [
    ]
