# Generated by Django 5.2.17 on 2026-10-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_merge_20261007_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricreference',
            name='reference_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='captured_image',
            field=models.TextField(blank=True),
        ),
    ]
