# Generated by Django 5.2.17 on 2026-10-08 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0007_resident_condominium_staff_condominium'),
        ('security', '0005_alter_biometricreference_reference_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitQrScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('VALID', 'Válido'), ('REJECTED', 'Denegado'), ('NOT_FOUND', 'Código desconocido')], max_length=20)),
                ('reason', models.CharField(max_length=40)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('scanned_token_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('visitor_name', models.CharField(blank=True, max_length=220)),
                ('visitor_document_number', models.CharField(blank=True, max_length=30)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('access_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='security.accessevent')),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='security.visitauthorization')),
                ('guard_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='condominiums.staff')),
                ('scanned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visit_qr_scan',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['-occurred_at'], name='idx_qr_scan_time'), models.Index(fields=['result', '-occurred_at'], name='idx_qr_scan_result'), models.Index(fields=['guard_staff', '-occurred_at'], name='idx_qr_scan_guard'), models.Index(fields=['scanned_token_hash'], name='idx_qr_scan_token')],
            },
        ),
    ]
