# Generated by Django 5.2.17 on 2026-08-09 17:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominiums', '0001_initial'),
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'asset_type',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('MAINTENANCE', 'Mantenimiento'), ('RETIRED', 'Retirado')], default='ACTIVE', max_length=20)),
                ('qr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='condominiums.sector')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='maintenance.assettype')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('frequency_days', models.IntegerField()),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='maintenance.asset')),
            ],
            options={
                'db_table': 'maintenance_plan',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_code', models.CharField(max_length=30, unique=True)),
                ('work_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('INSPECTION', 'Inspección')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('IN_PROGRESS', 'En progreso'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.asset')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('current_assignee_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='condominiums.staff')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='incidents.incident')),
                ('maintenance_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenanceplan')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='incidents.prioritylevel')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.supplier')),
            ],
            options={
                'db_table': 'work_order',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_order_actions', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_assignments', to='condominiums.staff')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='maintenance.workorder')),
            ],
            options={
                'db_table': 'work_order_assignment',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video'), ('DOCUMENT', 'Documento')], default='IMAGE', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_uploads', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.workorder')),
            ],
            options={
                'db_table': 'work_order_attachment',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='maintenance.workorder')),
            ],
            options={
                'db_table': 'work_order_cost_item',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'status'], name='idx_asset_type_status'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['sector'], name='idx_asset_sector'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['next_due_at'], name='idx_maintenance_plan_due'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('frequency_days__gt', 0)), name='chk_maintenance_frequency'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'scheduled_for'], name='idx_work_status_schedule'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['current_assignee_staff', 'status'], name='idx_work_assignee_status'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['asset', '-created_at'], name='idx_work_asset_time'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estimated_cost__isnull', True), ('estimated_cost__gte', 0), _connector='OR'), models.Q(('actual_cost__isnull', True), ('actual_cost__gte', 0), _connector='OR')), name='chk_work_order_costs'),
        ),
        migrations.AddConstraint(
            model_name='workorderassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('assigned_at')), _connector='OR'), name='chk_work_assignment_dates'),
        ),
        migrations.AddConstraint(
            model_name='workorderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('work_order',), name='uq_work_current_assignment'),
        ),
        migrations.AddIndex(
            model_name='workordercostitem',
            index=models.Index(fields=['work_order'], name='idx_work_cost_order'),
        ),
        migrations.AddConstraint(
            model_name='workordercostitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_work_cost_qty'),
        ),
        migrations.AddConstraint(
            model_name='workordercostitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='chk_work_cost_unit'),
        ),
    ]
