# Generated by Django 5.2.17 on 2026-08-09 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('REPORTED', 'Reportada'), ('REVIEWED', 'Revisada'), ('ASSIGNED', 'Asignada'), ('IN_PROGRESS', 'En progreso'), ('RESOLVED', 'Resuelta'), ('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada')], default='REPORTED', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='IncidentAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=60)),
                ('text_hash', models.CharField(max_length=64)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('suggested_staff_type', models.CharField(blank=True, choices=[('ADMINISTRATION', 'Administración'), ('SECURITY', 'Seguridad'), ('MAINTENANCE', 'Mantenimiento'), ('CLEANING', 'Limpieza'), ('OTHER', 'Otro')], max_length=20, null=True)),
                ('suggested_action', models.TextField(blank=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('CORRECTED', 'Corregido'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'incident_ai_analysis',
            },
        ),
        migrations.CreateModel(
            name='IncidentAIEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('text_value', models.CharField(max_length=240)),
                ('normalized_value', models.CharField(blank=True, max_length=240)),
                ('confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('applied_weight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'db_table': 'incident_ai_entity',
            },
        ),
        migrations.CreateModel(
            name='IncidentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'db_table': 'incident_assignment',
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video'), ('DOCUMENT', 'Documento')], default='IMAGE', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'incident_attachment',
            },
        ),
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('default_staff_type', models.CharField(blank=True, choices=[('ADMINISTRATION', 'Administración'), ('SECURITY', 'Seguridad'), ('MAINTENANCE', 'Mantenimiento'), ('CLEANING', 'Limpieza'), ('OTHER', 'Otro')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'incident_category',
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Público'), ('INTERNAL', 'Interno')], default='PUBLIC', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'incident_comment',
            },
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('REPORTED', 'Reportada'), ('REVIEWED', 'Revisada'), ('ASSIGNED', 'Asignada'), ('IN_PROGRESS', 'En progreso'), ('RESOLVED', 'Resuelta'), ('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'incident_status_history',
            },
        ),
        migrations.CreateModel(
            name='PriorityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('rank', models.SmallIntegerField(unique=True)),
                ('min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'priority_level',
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('entity_type', models.CharField(max_length=40)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'risk_rule',
            },
        ),
    ]
