# Generated by Django 5.2.17 on 2026-08-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominiums', '0001_initial'),
        ('incidents', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='maintenance.asset'),
        ),
        migrations.AddField(
            model_name='incident',
            name='current_assignee_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='condominiums.staff'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='condominiums.resident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='condominiums.sector'),
        ),
        migrations.AddField(
            model_name='incident',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='condominiums.unit'),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='reviewed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentaientity',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='incidents.incidentaianalysis'),
        ),
        migrations.AddField(
            model_name='incidentassignment',
            name='assigned_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incident_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentassignment',
            name='assigned_to_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_assignments', to='condominiums.staff'),
        ),
        migrations.AddField(
            model_name='incidentassignment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='suggested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='incidents.incidentcategory'),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidentcategory'),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='changed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='incidents.incident'),
        ),
        migrations.AddConstraint(
            model_name='prioritylevel',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gt', 0)), name='chk_priority_rank'),
        ),
        migrations.AddConstraint(
            model_name='prioritylevel',
            constraint=models.CheckConstraint(condition=models.Q(('min_score__isnull', True), ('max_score__isnull', True), ('max_score__gte', models.F('min_score')), _connector='OR'), name='chk_priority_score_range'),
        ),
        migrations.AddConstraint(
            model_name='prioritylevel',
            constraint=models.CheckConstraint(condition=models.Q(('target_minutes__isnull', True), ('target_minutes__gt', 0), _connector='OR'), name='chk_priority_target'),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='suggested_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='incidents.prioritylevel'),
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.prioritylevel'),
        ),
        migrations.AddIndex(
            model_name='riskrule',
            index=models.Index(fields=['is_active', 'entity_type'], name='idx_risk_active_type'),
        ),
        migrations.AddField(
            model_name='incidentaientity',
            name='risk_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_entities', to='incidents.riskrule'),
        ),
        migrations.AddIndex(
            model_name='incidentassignment',
            index=models.Index(fields=['assigned_to_staff', '-assigned_at'], name='idx_inc_assignment_staff'),
        ),
        migrations.AddConstraint(
            model_name='incidentassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('assigned_at')), _connector='OR'), name='chk_inc_assignment_dates'),
        ),
        migrations.AddConstraint(
            model_name='incidentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('incident',), name='uq_inc_current_assignment'),
        ),
        migrations.AddIndex(
            model_name='incidentattachment',
            index=models.Index(fields=['incident'], name='idx_inc_attachment_inc'),
        ),
        migrations.AddIndex(
            model_name='incidentcomment',
            index=models.Index(fields=['incident', 'created_at'], name='idx_inc_comment_time'),
        ),
        migrations.AddIndex(
            model_name='incidentstatushistory',
            index=models.Index(fields=['incident', 'changed_at'], name='idx_incident_history'),
        ),
        migrations.AddIndex(
            model_name='incidentaianalysis',
            index=models.Index(fields=['incident', '-created_at'], name='idx_ai_incident_time'),
        ),
        migrations.AddConstraint(
            model_name='incidentaianalysis',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='chk_ai_confidence'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='idx_inc_status_priority'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['current_assignee_staff', 'status'], name='idx_inc_assignee_status'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['category', '-created_at'], name='idx_inc_category_time'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(condition=models.Q(('status__in', ('REPORTED', 'REVIEWED', 'ASSIGNED', 'IN_PROGRESS'))), fields=['due_at'], name='idx_incident_due_open'),
        ),
        migrations.AddIndex(
            model_name='incidentaientity',
            index=models.Index(fields=['analysis'], name='idx_ai_entity_analysis'),
        ),
        migrations.AddConstraint(
            model_name='incidentaientity',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='chk_ai_entity_confidence'),
        ),
    ]
