# Generated by Django 5.2.17 on 2026-08-09 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('ALL', 'Todos'), ('RESIDENTS', 'Residentes'), ('STAFF', 'Personal'), ('SECURITY', 'Seguridad'), ('MAINTENANCE', 'Mantenimiento'), ('DIRECTIVE', 'Directiva')], default='ALL', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement',
                'indexes': [models.Index(fields=['status', '-published_at'], name='idx_announcement_publish')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('published_at__isnull', True), ('expires_at__gt', models.F('published_at')), _connector='OR'), name='chk_announcement_expiry')],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_token',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_device_user_active')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('resource_type', models.CharField(blank=True, max_length=60, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=80, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ('-created_at',),
                'indexes': [models.Index(condition=models.Q(('read_at__isnull', True)), fields=['user', '-created_at'], name='idx_notification_unread')],
            },
        ),
    ]
