# Generated by Django 5.2.17 on 2026-08-09 17:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_systempermission_is_active_systempermission_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('timezone', models.CharField(default='America/La_Paz', max_length=50)),
                ('logo', models.CharField(blank=True, max_length=500)),
                ('rules_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condominium',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('BLOCKED', 'Bloqueado')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resident', to='accounts.person')),
            ],
            options={
                'db_table': 'resident',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('sector_type', models.CharField(choices=[('SECTOR', 'Sector'), ('BLOCK', 'Bloque'), ('TOWER', 'Torre'), ('FLOOR', 'Piso'), ('ZONE', 'Zona'), ('OTHER', 'Otro')], default='SECTOR', max_length=20)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='condominiums.condominium')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='condominiums.sector')),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('staff_type', models.CharField(choices=[('ADMINISTRATION', 'Administración'), ('SECURITY', 'Seguridad'), ('MAINTENANCE', 'Mantenimiento'), ('CLEANING', 'Limpieza'), ('OTHER', 'Otro')], max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('SUSPENDED', 'Suspendido')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='accounts.person')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('unit_type', models.CharField(choices=[('HOUSE', 'Casa'), ('APARTMENT', 'Departamento'), ('OFFICE', 'Oficina'), ('STORE', 'Local'), ('OTHER', 'Otro')], default='APARTMENT', max_length=20)),
                ('floor_label', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('INACTIVE', 'Inactiva'), ('MAINTENANCE', 'Mantenimiento')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='condominiums.sector')),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='ResidentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('OWNER', 'Propietario'), ('TENANT', 'Inquilino'), ('FAMILY', 'Familiar'), ('AUTHORIZED', 'Autorizado'), ('OTHER', 'Otro')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_links', to='condominiums.resident')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_links', to='condominiums.unit')),
            ],
            options={
                'db_table': 'resident_unit',
            },
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['parent'], name='idx_sector_parent'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('condominium', 'code'), name='uq_sector_code'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_type', 'status'], name='idx_staff_type_status'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('hire_date__isnull', True), ('end_date__gte', models.F('hire_date')), _connector='OR'), name='chk_staff_dates'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['sector'], name='idx_unit_sector'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status'], name='idx_unit_status'),
        ),
        migrations.AddIndex(
            model_name='residentunit',
            index=models.Index(fields=['unit'], name='idx_resident_unit_unit'),
        ),
        migrations.AddConstraint(
            model_name='residentunit',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='chk_resident_unit_dates'),
        ),
        migrations.AddConstraint(
            model_name='residentunit',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('resident', 'unit'), name='uq_resident_unit_active'),
        ),
        migrations.AddConstraint(
            model_name='residentunit',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('resident',), name='uq_resident_primary_active'),
        ),
    ]
