# Generated by Django 5.2.17 on 2026-10-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0005_sync_condominium_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominium',
            name='max_residents',
            field=models.PositiveIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='condominium',
            name='max_units',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='condominium',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='condominium',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
