# Generated by Django 5.2.17 on 2026-10-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0006_condominium_max_residents_condominium_max_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='condominiums.condominium'),
        ),
        migrations.AddField(
            model_name='staff',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='condominiums.condominium'),
        ),
    ]
